<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addpaste extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('paste', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'content' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'language' => 
             array(
              'type' => 'string',
              'length' => 20,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_bin',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('paste');
    }
}