<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('paste', 'hash_id', 'string', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('paste', 'hash_id');
    }
}