<?php

/**
 * PasteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PasteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PasteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Paste');
    }
}