<?php

/**
 * Paste
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Paste extends BasePaste
{
	public function preInsert($event)
	{
		$hash_id = substr(hash('sha512', $this->content . time() . rand(0, 255)), 0, 8);
		$this->_set('hash_id', $hash_id);
	}
}